#!/usr/bin/env bash
#
# toggle_icloud.sh


osversion=$(sw_vers | grep "ProductVersion:" | cut -f3 | cut -d. -f1)

# Privacy Relay
if [[ $osversion -ge 13 ]]; then
    osascript control_private_relay.scpt
else
    osascript control_private_relay_older_mac.scpt
fi

